jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Build
      run: ./gradlew check jacoco assemble
    - continue-on-error: true
      name: Codecov
      uses: codecov/codecov-action@v3
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
